[theme]
primaryColor = "#007FFF"                  # Azul ardósia → Botões e destaques
backgroundColor = "#D9E5F7"              # Branco → Fundo principal (limpo e leve)
secondaryBackgroundColor = "#ADD8E6"     # Azul claro → Caixas de texto, sidebar etc.
textColor = "#1E2B6B"                    # Azul puro → Texto principal
font = "sans serif"
